
server:
  port: 8081

spring:
  application:
    name: ORDER-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:3307/OrderService
    username: postgres
    password: Kishan@M3153

  jpa:
    hibernate:
      ddl-auto: update
    format_sql: true
    show-sql: true


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true




